In [1]:
import numpy as np

In [2]:
def single_neuron(inputs:list, weights:list, bias=float)->float:
    output = np.dot( inputs, weights ) + bias
    return output

In [12]:
n_inputs = 10

In [13]:
# Create inputs of 10 observations with 5 features
inputs = np.random.randn(1,n_inputs)
inputs

array([[-0.86696297,  0.64836242, -0.45275371, -2.45457559,  0.41164961,
         0.14791244,  1.23798392, -0.12211418, -0.92853784, -0.02523725]])

In [14]:
weights = 0.01 * np.random.randn(n_inputs,1)
weights

array([[ 0.00102091],
       [ 0.00286891],
       [-0.00072515],
       [-0.00731011],
       [ 0.00926133],
       [-0.00199691],
       [-0.01107394],
       [ 0.01837288],
       [ 0.00851767],
       [ 0.00627896]])

In [15]:
bias = 2.0

In [16]:
output = single_neuron(inputs, weights, bias)
output

array([[1.9987432]])